name: "Feature Request"
about: "Use this template for submitting feature requests."

title: "[Feature Request] "

on:
  issues:
    labels:
      - "enhancement"
    projects:
      - "Feature Requests"

body:

## Description
Please provide a detailed description of the feature you're requesting.

## Context
Describe the context or problem you're trying to solve with this feature request.

## Additional Information
Add any other relevant information or screenshots here.

## Acceptance Criteria
Define the criteria that must be met for this feature to be considered complete.

## Due Date
Set a due date if necessary.

## Assignees
Assign someone to this issue if applicable.

## Labels
Add any additional labels that may be relevant.

## Attachments
If applicable, attach files or screenshots here.

## Additional Comments
Any additional information or comments.
