name: "Issue Template"
about: "Template for creating issues"
title: "[Feature] "

# Default values for your issue:
defaults:
  assignees:
    - "username"
  labels:
    - "enhancement"
  milestone: "Sprint X"
  projects:
    - "Project Name"



## Tasks
- "[ ] Task 1"
- "[ ] Task 2"
- "[ ] ..."

## Acceptance Criteria
- "[ ] Criterion 1"
- "[ ] Criterion 2"
- "[ ] ..."

## Additional Context
"Include any additional relevant information."

## Attachments
"If applicable, attach files or screenshots here."

## Due Date
"Set a due date if necessary."

## Other Comments
"Any additional information or comments."
