name: Issue Template
about: Template for creating issues
title: "[Feature] "

# Default values for your issue:
defaults:
  assignees:
    - username
  labels:
    - enhancement
  milestone: Sprint X
  projects:
    - Project Name

body:

## Description
[Replace this paragraph with a detailed description of the issue.]

## Tasks
- [ ] Task 1
- [ ] Task 2
- [ ] ...

## Acceptanc



