---
name: Nom_de_l'Issue_Template
about: Description brève de l'issue
title: "[Tâche] "

---

## Description
[Remplacez ce paragraphe par une description détaillée de l'issue.]

## Tâches
- [ ] Tâche 1
- [ ] Tâche 2
- [ ] ...

## Critères d'Acceptation
- [ ] Critère 1
- [ ] Critère 2
- [ ] ...

## Contexte Additionnel
[Incluez ici toute information contextuelle pertinente.]

## Attachements
[Si applicable, joignez des fichiers ou des captures d'écran ici.]

## Labels
[Assignez les labels appropriés à cette issue.]

## Assigné à
[Assignez cette issue à un ou plusieurs membres de l'équipe.]

## Échéance
[Fixez une date limite si nécessaire.]

## Autres Commentaires
[Toute information ou commentaire supplémentaire.]


